import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import UserInitialDataProvider from '@/providers/UserInitialDataProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SSMS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <UserInitialDataProvider>{children}</UserInitialDataProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
